#include <signal.h>

#include <stdio.h>

void rotina(int p){
    printf("Nao vou terminar!");
    sleep(2);
}

// A ROTINA SIGNAL VAI VINCULAR A ROTINA COM O SINAL
// SE CHEGAR O SIGINT, ELE VAI PARAR NAO IMPORTA O QUE ESTA FAZENDO E VAI FAZER A ROTINA
// SIGNAL FAZ NO INICIO DO PROGRAMA, IRA INSTALAR A ROTINA
main(){
    int i = 0;
    signal(SIGINT, rotina);
    signal(SIGHUP, rotina);

    // LOOPING INFINITO, DEVE-SE ABRIR OUTRO TERMINAL E ENVIAR UM SINAL PARA ELE
    // SE ENVIAR OUTRO SINAL QUE NAO SEJA O SIGINT NEM O SIGHUP, NAO OCORRERÁ NADA
    while(1){
        printf("%d \n", i++);
    }
}

// PARA ENVIAR UM SINAL PRO PROCESSO, TEMOS QUE VER O PID DO PROCESSO
// POSSO USAR O COMANDO "KILL -SIGINT 4589" EM QUE 4589 É O PID DO PROCESSO POR EXEMPLO
// QUANDO DOU O CTRL C, O DRIVER DO SO ENVIA UM SIGINT PARA O PROCESSO, CASO ELE NAO TRATE 
// O SINAL SIGINT, IRÁ ENCERRAR O PROCESSO, AGORA SE TRATAR, IRA FAZER O QUE FOI DEFINIDO NO TRATAMENTO

// EXTRA: O SEGMENTATION FAULT É RECEBIDO, CASO O PROCESSO FAÇA ACESSO INDEVIDO A MEMORIA E O HARDWARE QUE CONTROLA A MEMORIA PERCEBE ESSE ACESSO
// E NOTIFICA O SO, O QUAL IRA ENVIAR UM SIGNAL AO PROCESSO. O SEMELHANTE OCORRE COM A DIVISAO POR 0 POR EXEMPLO.

//kill -l é o comando que verifica os tipos de sinais que podem ser enviar para um processo.